.\" revdep.d(5) manual page
.\" See COPYING and COPYRIGHT files for corresponding information.
.Dd November 12, 2024
.Dt REVDEP.D 5
.Os
.\" ==================================================================
.Sh NAME
.Nm revdep.d
.Nd configuration directory for revdep
.\" ==================================================================
.Sh SYNOPSIS
.Nm /etc/revdep.d/\&*
.\" ==================================================================
.Sh DESCRIPTION
TODO
.\" ==================================================================
.Sh EXAMPLES
TODO
.Bd -literal -offset indent
#
# /etc/revdep.d/apulse: ... configuration
#
# See revdep.d(5) for more information.
#

/usr/lib/apulse

# End of file.
.Ed
.Pp
All lines which begin with the
.Qo Li # Qc
character are comments and will not be parsed.
.\" ==================================================================
.Sh SEE ALSO
.Xr revdep 8
.\" vim: cc=72 tw=70
.\" End of file.
