#!/bin/sh
#
# $Id: prtcreate,v 1.1.1.2 2017/04/17 02:23:32 opel Exp $
# (c) 2003 by Martin Opel <martin@obbl-net.de>
# (c) 2017 by The CRUX Project
#
# May be redistributed and modified under the terms of the GPL
# only usable with CRUX Linux, version 1.0 or higher.
#
# USE AT YOUR OWN RISK
#
# This script creates a Pkgfile in the current working directory with
# all necessary header information fields and an empty build() function.
# The port name is the name of the current working directory.

if [ -f Pkgfile ]; then
	echo "Pkgfile exists!"
	exit 1
fi

if [ -f /etc/prtcreate.conf ]; then
	. /etc/prtcreate.conf
fi

cat <<EOF > Pkgfile
# Description:
# URL:
# Maintainer:$(echo " $maintainer_line")
# Depends on:

name=`basename $PWD`
version=
release=1
source=()

build() {
	cd \$name-\$version
}
EOF
