name: Build CI

on:
  push:
    branches: [ "master" ]
    paths: &paths
      - "meson.build"
      - "meson.options"
      - "meson_options.txt"
      - "src/**"
      - "man/**"
      - "completion/**"
      - "vim/**"
      - ".github/**"

  pull_request:
    branches: [ "master" ]
    paths: *paths

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - name: glibc
            container: ""
            install: |
              sudo apt-get update
              sudo apt-get install -y \
                meson ninja-build pkg-config g++ \
                scdoc libelf-dev
          - name: musl
            container: "alpine:latest"
            install: |
              apk add --no-cache \
                build-base meson ninja pkgconf g++ \
                scdoc elfutils-dev zlib-static zstd-static

        cfg:
          - name: shared
            link_mode: shared
          - name: static
            link_mode: static

    name: ${{ matrix.env.name }} / ${{ matrix.cfg.name }}
    container: ${{ matrix.env.container != '' && matrix.env.container || null }}

    steps:
      - uses: actions/checkout@v4

      - name: Checkout librevdep
        uses: actions/checkout@v4
        with:
          repository: zeppe-lin/librevdep
          path: librevdep

      - name: Install build dependencies
        run: ${{ matrix.env.install }}

      - name: Configure librevdep
        run: |
          meson setup build-librevdep librevdep \
            --buildtype=plain \
            --wrap-mode=nodownload \
            --prefix=/usr \
            -D b_lto=false \
            -D b_pie=true

      - name: Build librevdep
        run: meson compile -C build-librevdep -v

      - name: Configure revdep
        env:
          PKG_CONFIG_PATH: ${{ github.workspace }}/build-librevdep/meson-uninstalled
        run: |
          pkg-config --modversion librevdep
          meson setup build \
            --buildtype=plain \
            --wrap-mode=nodownload \
            --prefix=/usr \
            --sysconfdir=/etc \
            --localstatedir=/var \
            -D b_lto=false \
            -D b_pie=true \
            -D link_mode=${{ matrix.cfg.link_mode }}

      - name: Build revdep
        env:
          PKG_CONFIG_PATH: ${{ github.workspace }}/build-librevdep/meson-uninstalled
        run: meson compile -C build -v

      - name: Install revdep to staging
        env:
          PKG_CONFIG_PATH: ${{ github.workspace }}/build-librevdep/meson-uninstalled
        run: DESTDIR="$PWD/stage" meson install -C build
