name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libelf-dev (elfutils)
      run: sudo apt-get install -y libelf-dev
    - name: Check PODs for errors
      run: podchecker *.pod
    - name: make
      run: make
