name: Lint CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install lint dependencies
      run: sudo apt-get install -y shellcheck mandoc

    # FIXME: fix completion lint errors
    #- name: Check completion scripts for errors
    #  run: cd completion && make lint

    - name: Check man pages for errors
      run: cd man && make lint

# End of file.
