name: Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y libelf-dev cppcheck

    - name: Check PODs for errors
      run: make -f utils.mk podchecker

    - name: Static C/C++ code analysis
      run: make -f utils.mk cppcheck

    - name: Build
      run: make

# End of file.
